version: "3.4"

services:
    api:
        image: "containerregistryarianahorvath30441.azurecr.io/arianahorvath30441backend:latest"
        domainname: "arianahorvath30441backend"
        ports: 
          - 8080:8080
        environment:
          SPRING_RABBITMQ_HOST: rabbitmq
          DB_IP: demo-db
          RABBIT_IP: demo-rabbit
          DB_PORT: 3307
          DB_USER: root
          DB_PASSWORD: root123
          DB_DBNAME: energy_utility
        deploy:
          resources:
            reservations:
              cpus: '1'
              memory: 2G

    db:
        image: "containerregistryarianahorvath30441.azurecr.io/db:latest"
        environment:
          MYSQL_DATABASE: energy_utility
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_HOST_AUTH_METHOD: trust
        domainname: "arianahorvath30441backend"
        ports:
          - 3307:3307
        deploy:
          resources:
            reservations:
              cpus: '1'
              memory: 2G
    rabbitmq:
        image: "containerregistryarianahorvath30441.azurecr.io/rabbitmq:latest"
        domainname: "arianahorvath30441backend"
        ports:
          - 15672:15672
          - 5672:5672
        deploy:
          resources:
            reservations:
              cpus: '1'
              memory: 2G