version: '3'

services:

  database:
    image: mysql

    restart: always
    environment:
      - MYSQL_DATABASE=energy_utility
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_HOST_AUTH_METHOD=trust
    ports:
      - "3307:3306"
    container_name: database

  backend:
    image: arianahorvath30441backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_IP=demo-db
      - RABBIT_IP=demo-rabbit
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_DBNAME=energy_utility

